### ISSUE TITLE
Compatibilidade Android 4.1.2

### ISSUE THREAD

**Issue by alexandremsouza1** [michaelrbk/showCaseCordova#4]
Como eu faço para ter a variável cordova como global em android antigo?

Baixando o projeto direto na google play o app roda sem problemas, porém compilando no cordova ele não roda nenhum plugin.

Testando em android 5.1 o app compilado roda sem problemas também.

**Comment by marcioggs** [comment]
Olá!
As bibliotecas dos plugins não vem no código fonte deste GIT, precisando ser baixadas separadamentes através de linha de comando.
Você chegou a fazer esta parte?
Aqui ensina como: https://stackoverflow.com/a/48296822

**Comment by alexandremsouza1** [comment]
Entendi.
Explicando melhor.
Tenho dois aparelhos: um Android 4.1 e outro 5.1.
No momento do deploy, npm run Android,  só o Android 5.1 funcionou 100% o outro até  fez o deploy sem erros mas quando eu clicava nos menus não acontecia nada. "Cordova is not defined".
Quanto aos plugins, o próprio npm fez a instalação automaticamente.
Outro teste que eu fiz foi baixar o app na play store nos dois celulares e rodou sem problemas nos dois. Por isso  a dúvida, para saber se existe algo a ser feito antes do deploy. 
Abraço  e parabéns pelo projeto.

**Comment by marcioggs** [comment]
Está utilizando qual versão do Cordova?
Verifica se ela é compatível com Android 4.1.

Aparece algum registro do erro no logcat? O que ele diz?

**Comment by alexandremsouza1** [comment]
Cordova cli 8.1.
Com a versão 7 também a mesma coisa.
O logcat diz: cordova undefined. 
Vc gerou o apk em qual versão do cordova?

**Comment by marcioggs** [comment]
Fala, Alexandre. 

Provavelmente testamos na versão 5 ou 4.
Testa com uma dessas e me avisa se funcionou.

Boa sorte.

**Comment by alexandremsouza1** [comment]
Fiz o teste e não obtive sucesso pois a cada vez que retrocedia o CLI de versão as outras coisas paravam de funcionar , como o gradle , java, etc.
